name: Automatically labeling with a special branch

on:
  pull_request:
    branches:
      - 'feat/**'

jobs:
  auto-labeling:
    runs-on: ubuntu-latest
    steps:

    - name: Add label
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const repoData = {
            owner: context.repo.owner,
            repo: context.repo.repo,
            issue_number: context.issue.number,
          }
          const name = context.payload.pull_request.base.ref
            .substr(5)
            .replace(/_/g, '-')

          await github.issues.getLabel({ ...repoData, name })
            .catch(() => {
              const colors = [ 'ff83aa', 'be8359', '2e8359', '6f556f', '5638e2' ]
              const color = colors[name.charCodeAt(0) % colors.length]
              return github.issues.createLabel({ ...repoData, name, color })
            })

          await github.issues.addLabels({ ...repoData, labels: [ name ] })
