name: List Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/github-script@v4
      id: set-result
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const now = Date.now();
          const oneHour = 60 * 60 * 1000;
          const activePulls = [];

          const { data } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })

          for (const pr of data) {
            const updatedAt = new Date(pr.updated_at).getTime();

            activePulls.push(`${pr.number}|${pr.head.ref}`);
          }

          return activePulls.join(';');
        result-encoding: string

    - name: Show Result
      run: >
        echo "${{steps.set-result.outputs.result}}" |
        sed 's/;/\n/g' |
        awk -F'|' '{
          print "Closing Rreview App: By version";
          cmd="echo "$1 "test "$2;
          system(cmd)
        }'



