name: List Pull Requests

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })
          .then(({ data }) => {
            for (const pr of data) {
              console.log('HEAD_REF: ', pr.head.ref);
              console.log('PR_NUMBER: ', pr.number);
              console.log('PR_UPDATED_AT: ', pr.updated_at);
            }
          });
