name: My First Action

on:
  pull_request:
    types:
      - opened
      - synchronize

env:
  BUILD_NUM: pr-${{ github.event.pull_request.number }}

jobs:
  commit-to-comment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🤖 Please click the link below:<br/>[https://${{ env.BUILD_NUM }}.example.com](https://${{ env.BUILD_NUM }}.example.com)`
          })
