name: My First Action

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches-ignore:
      - 'chore/**'

env:
  BUILD_NUM: pr-${{ github.event.pull_request.number }}

jobs:
  do-somethings:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: 'Run script'
      run: |-
        ./push.sh ${{ github.base_ref }} ${{ github.head_ref }} 

  commit-to-comment:
    if: github.event.action == 'opened'
    needs: do-somethings
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2


    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🤖 Please click the link below:<br/>[https://${{ env.BUILD_NUM }}.example.com](https://${{ env.BUILD_NUM }}.example.com)`
          })
