name: My First Action

on:
  pull_request:
    types:
      - labeled
      - unlabeled

env:
  BUILD_NUM: pr-${{ github.event.pull_request.number }}

jobs:
  do-somethings:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'bug') }}
    runs-on: ubuntu-latest


    steps:
        
      - uses: actions/github-script@v4
        id: set-result
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: [ 'review' ]
            })