name: Scheduled Closing Reviews

on:
  schedule:
    # https://crontab.guru/every-hour
    - cron: '0 */1 * * *'

jobs:
  merge_schedule:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/github-script@v4
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const now = Date.now();
          const oneHour = 60 * 60 * 1000;
          const activePulls = [];

          const { data } = await github.pulls.list({
            owner: context.repo.owner,
            repo: context.repo.repo,
          })

          for (const pr of data) {
            const updatedAt = new Date(pr.updated_at).getTime();
            if (now - updatedAt > oneHour) {
              github.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: pr.number,
                name: 'review'
              })
            }
          }
